Introduce git_gc_prune_date
We sometimes receive errors like below
so we want to adjust the value:

```
git stdout: Nothing written
git stderr: Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
error: The last gc run reported the following. Please correct the root cause
and remove gc.log.
Automatic cleanup will not be performed until the file is removed.
```